version: '3'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: test_db
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
    - ./db/init:/docker-entrypoint-initdb.d
    - ./db/data:/var/lib/mysql
    ports:
    - 3306:3306